services:

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - redis-data:/data


  mongodb:
    image: mongo:7
    container_name: mongo-container

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: redis_db

    volumes:
      - mongo-data:/data/db


volumes:
  redis-data:
  mongo-data: